name: Pull-Request
on:
  pull_request:
    types: [opened, synchronize, closed]
permissions:
  contents: write

jobs:
  lint:
    if: github.event.action != 'closed'
    name: Run Linter
    uses: gumbandapp/gumband-workflows/.github/workflows/lint.yaml@main
    secrets: inherit
  depcheck:
    if: github.event.action != 'closed'
    name: Check Dependencies
    uses: gumbandapp/gumband-workflows/.github/workflows/depcheck.yaml@main
    secrets: inherit
  audit:
    if: github.event.action != 'closed'
    name: Audit
    uses: gumbandapp/gumband-workflows/.github/workflows/audit.yaml@main
    secrets: inherit
  unit-test:
    if: github.event.action != 'closed'
    name: Unit Test
    uses: gumbandapp/gumband-workflows/.github/workflows/unit-test.yaml@main
    secrets: inherit
  # integration-test:
  #   if: github.event.action != 'closed'
  #   name: Integration Test
  # needs:
  #   - lint
  #   - depcheck
  #   - audit
  #   - unit-test
  # uses: gumbandapp/gumband-workflows/.github/workflows/integration-test.yaml@main
  # secrets: inherit
  build-and-push-docker-image:
    if: github.event.action != 'closed'
    name: Build and Push Docker Image
    needs:
      - lint
      - audit
      - depcheck
      - unit-test
    uses: gumbandapp/gumband-workflows/.github/workflows/build-and-push-docker-image.yaml@main
    secrets: inherit
  build-and-push-storybook:
    if: github.event.action != 'closed'
    name: Build and Push Storybook
    needs:
      - lint
      - audit
      - depcheck
      - unit-test
    uses: gumbandapp/gumband-workflows/.github/workflows/build-and-push-storybook.yaml@main
    secrets: inherit
  create-preview-environment:
    if: github.event.action != 'closed'
    needs: build-and-push-docker-image
    name: Create Preview Environment
    uses: gumbandapp/gumband-workflows/.github/workflows/vcluster-create.yaml@main
    secrets: inherit
  update-preview-environment:
    if: github.event.action == 'synchronize' && github.event.action != 'closed'
    needs: create-preview-environment
    name: Update Preview Environment
    uses: gumbandapp/gumband-workflows/.github/workflows/vcluster-update.yaml@main
    secrets: inherit
  delete-preview-environment:
    if: github.event.action == 'closed'
    name: Delete Preview Environment
    uses: gumbandapp/gumband-workflows/.github/workflows/vcluster-delete.yaml@main
    secrets: inherit
  delete-deploy-key:
    if: github.event.action == 'closed'
    needs: delete-preview-environment
    name: Delete Preview Environment
    uses: gumbandapp/gumband-workflows/.github/workflows/delete-deployment-key.yaml@main
    secrets: inherit
